=== jorge-ls/ARSO/arso-proyecto/Entrega1/xml/ejercicio1-1.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ciudad (nombre, pais, poblacion, ubicacion, dbpedia?, wikipedia?, informacionmeteorologica?, sitio*)>
<!ATTLIST ciudad codigo CDATA #REQUIRED
				 fechaactualizacion CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT ubicacion (latitud, longitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT dbpedia (#PCDATA)>
<!ELEMENT wikipedia (#PCDATA)>
<!ELEMENT informacionmeteorologica (nombreestacion, temperatura, nubes)>
<!ATTLIST informacionmeteorologica fechayhora CDATA #REQUIRED>
<!ELEMENT nombreestacion (#PCDATA)>
<!ELEMENT temperatura (#PCDATA)>
<!ELEMENT nubes (#PCDATA)>
<!ELEMENT sitio (nombre)>
<!ATTLIST sitio codigo NMTOKEN #REQUIRED>

=== jorge-ls/ARSO/arso-proyecto/Entrega1/xml-bd/ejercicio1-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ciudad SYSTEM "../xml/ejercicio1-1.dtd" >
<ciudad codigo="2520058" fechaactualizacion="2012-03-04">
  <nombre>Cartagena</nombre>
  <pais>Spain</pais>
  <poblacion>211996</poblacion>
  <ubicacion>
    <latitud>37.60512</latitud>
    <longitud>-0.98623</longitud>
  </ubicacion>
  <dbpedia>http://dbpedia.org/resource/Cartagena%2C_Spain</dbpedia>
  <wikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Spain</wikipedia>
  <informacionmeteorologica fechayhora="2019-02-04 12:00:00">
  	<nombreestacion> International airport of the Region of Murcia</nombreestacion>
  	<temperatura>13</temperatura>
  	<nubes>clouds and visibility OK</nubes>
  </informacionmeteorologica>
  	<sitio codigo="10860321">
  		<nombre>Parque Maestranza de Arrtilleria</nombre>
  	</sitio>
  	<sitio codigo="10280776">
  		<nombre>Museo Hist√≥rico Militar de Cartagena</nombre>
  	</sitio>
  
</ciudad>
