=== jorge-ls/ARSO/arso-proyecto/Entrega1/xml/ejercicio1-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/ejercicio1-2"
	xmlns:tns="http://www.example.org/ejercicio1-2"
	elementFormDefault="qualified">
	
	<complexType name="tipo_ubicacion">
		<sequence>
			<element name="latitud" type="decimal" />
			<element name="longitud" type="decimal" />
		</sequence>
	</complexType>
	
	<complexType name="tipo_informacionmeteorologica">
	 	<sequence>
	 		<element name="fechayhora" type="dateTime" />
	 		<element name="nombreestacion" type="string" />
	 		<element name="temperatura" type="decimal" />
	 		<element name="nubes" type="string" />
	 	</sequence>
	 </complexType>
	
	<complexType name="tipo_sitio">
		<sequence>
			<element name="nombre" type="string" />
		</sequence>
		<attribute name="codigo" type="string" use="required" />
	</complexType>
	
	<complexType name="tipo_libro">
		<sequence>
			<element name="titulo" type="string" />
			<element name="isbn" type="string" minOccurs="0" />
			<element name="urlImagen" type="string" />
			<element name="urlWeb" type="string" />
		</sequence>
		<attribute name="id" type="string" use="required" />
	</complexType>
	
	<element name="ciudad">
		<complexType>
			<sequence>
				<element name="nombre" type="string" />
				<element name="pais" type="string" />
				<element name="poblacion" type="int" />
				<element name="ubicacion" type="tns:tipo_ubicacion" />
				<element name="dbpedia" type="string" minOccurs="0" />
				<element name="wikipedia" type="string" minOccurs="0" />
				<element name="fechaactualizacion" type="date" />
				<element name="informacionmeteorologica" minOccurs="0" type="tns:tipo_informacionmeteorologica" />
				<element name="sitio" minOccurs="0" maxOccurs="unbounded" type="tns:tipo_sitio" />
				<element name="libro" type="tns:tipo_libro" minOccurs="0" maxOccurs="3" />
			</sequence>
			<attribute name="codigo" type="string" use="required"	/>
		</complexType>
	</element>
</schema>

=== jorge-ls/ARSO/arso-proyecto/Entrega1/xml-bd/2520058.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 ../xml/ejercicio1-2.xsd" codigo="2520058"><nombre>Cartagena</nombre><pais>Spain</pais><poblacion>211996</poblacion><ubicacion><latitud>37.60512</latitud><longitud>-0.98623</longitud></ubicacion><dbpedia>http://dbpedia.org/resource/Cartagena%2C_Spain</dbpedia><wikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Spain</wikipedia><fechaactualizacion>2012-03-04</fechaactualizacion><informacionmeteorologica><fechayhora>2019-04-26T22:00:00</fechayhora><nombreestacion>International airport of the Region of Murcia</nombreestacion><temperatura>14.0</temperatura><nubes>no clouds detected</nubes></informacionmeteorologica><sitio codigo="10860321"><nombre>Parque Maestranza de Artilleria</nombre></sitio><sitio codigo="10280776"><nombre>Museo Histórico Militar de Cartagena</nombre></sitio><sitio codigo="10280775"><nombre>Parque Arqueológico Cerro del Molinete</nombre></sitio><sitio codigo="10280774"><nombre>Barrio del Foro Romano</nombre></sitio><sitio codigo="6505996"><nombre>SERCOTEL Carlos III</nombre></sitio><sitio codigo="10170453"><nombre>Sercotel Alfonso Xiii Ex-Best Western</nombre></sitio><sitio codigo="6483755"><nombre>Sercotel Alfonso XIII</nombre></sitio><sitio codigo="10400375"><nombre>Plaza San Francisco</nombre></sitio><sitio codigo="6482678"><nombre>HUSA CARTAGONOVA Hotel &amp; Spa</nombre></sitio></ciudad>

=== jorge-ls/ARSO/arso-proyecto/Entrega1/xml-bd/ejercicio1-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciudad codigo="2520058"
	xmlns="http://www.example.org/ejercicio1-2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 ../xml/ejercicio1-2.xsd ">
  <nombre>Cartagena</nombre>
  <pais>Spain</pais>
  <poblacion>211996</poblacion>
  <ubicacion>
    <latitud>37.6512</latitud>
    <longitud>-0.98623</longitud>
  </ubicacion>
  <dbpedia>http://dbpedia.org/resource/Cartagena%2C_Spain</dbpedia>
  <wikipedia>http://en.wikipedia.org/wiki/Cartagena%2C_Spain</wikipedia>
  <fechaactualizacion>2012-03-04</fechaactualizacion>
  <informacionmeteorologica>
  	<fechayhora>2019-02-04T12:00:00</fechayhora>
  	<nombreestacion>International airport of the Region of Murcia</nombreestacion>
  	<temperatura>13</temperatura>
  	<nubes>clouds and visibility OK</nubes>
  </informacionmeteorologica>
  <sitio codigo="10860321">
	<nombre>Parque Maestranza de Artilleria</nombre>
  </sitio>
  <sitio codigo="10280776">
	<nombre>Museo Hist√≥rico Militar de Cartagena</nombre>
  </sitio>
</ciudad>

=== jorge-ls/ARSO/arso-proyecto/Entrega1/xml-bd/3687238.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio1-2 ../xml/ejercicio1-2.xsd" codigo="3687238"><nombre>Cartagena</nombre><pais>Colombia</pais><poblacion>952024</poblacion><ubicacion><latitud>10.39972</latitud><longitud>-75.51444</longitud></ubicacion><dbpedia>http://dbpedia.org/resource/Cartagena%2C_Colombia</dbpedia><wikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Colombia</wikipedia><fechaactualizacion>2018-04-20</fechaactualizacion><informacionmeteorologica><fechayhora>2019-04-26T22:00:00</fechayhora><nombreestacion>Cartagena / Rafael Nunez</nombreestacion><temperatura>31.0</temperatura><nubes>broken clouds</nubes></informacionmeteorologica><sitio codigo="3687237"><nombre>Acueducto Cartagena</nombre></sitio><sitio codigo="3689976"><nombre>Amberes</nombre></sitio><sitio codigo="3689126"><nombre>Barrio El Prado</nombre></sitio><sitio codigo="3689554"><nombre>Armenia</nombre></sitio><sitio codigo="3688474"><nombre>Bruselas</nombre></sitio><sitio codigo="9612088"><nombre>Movich Hotel Cartagena De Indias Slh</nombre></sitio><sitio codigo="9222770"><nombre>Cartagena Water Treatment Plant</nombre></sitio><sitio codigo="3675258"><nombre>Lomas de Mari√≥n</nombre></sitio><sitio codigo="10233251"><nombre>Hotel Avenida Buenos Aires</nombre></sitio></ciudad>
